export const USER_KEY = "offliner:user";
export const OFFLINIUM_DELIVERY_INTERVAL = 10 * 1000;
export const COMPANION_INVOCATION_COST = 60 * 6;
export const COMPANION_INVOCATION_OFFLINE_MS = 60 * 1000;
export const HOUSE_CONSTRUCTION_COST = 120 * 6;
export const HOUSE_CONSTRUCTION_OFFLINE_MS = 2 * 60 * 1000;
export const COMPANIONS_PER_HOUSE = 4;
